# Generated by Django 4.1.5 on 2023-02-01 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=30)),
                ('Stock', models.IntegerField()),
                ('Item_desc', models.TextField(null=True)),
                ('To_use_video', models.FileField(null=True, upload_to='{%  static "videos/" %}', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('Item_desc_video', models.FileField(null=True, upload_to='{%  static "videos/" %}', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.CreateModel(
            name='Item_variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variation_name', models.CharField(max_length=20)),
                ('img1', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('img2', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('img3', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('img4', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('img5', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('img6', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('img7', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('img8', models.ImageField(null=True, upload_to="{% static 'images/' %}")),
                ('Variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
        ),
    ]
